/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars = {
  tutorial: [{type: 'autogenerated', dirName: '.'}],
  sdk: [{type: 'autogenerated', dirName: 'sdk'}],
  vocdoniApi: [
    {
      type: "category",
      label: "Vocdoni",
      link: {
        type: "generated-index",
        title: "Vocdoni API",
        description:
          "The Vocdoni API (API) would be the main entry point for using the underlying Vocdoni Open Stack.",
        slug: "/category/vocdoni-api",
      },
      items: require("./docs/vocdoni-api/sidebar.js"),
    },
  ],
};

module.exports = sidebars;
