const sidebarLabelOrder = {
  'Getting Started': 0, // First
  'Vocdoni SDK': 1,
  'Vocdoni API': 2,
  'UI Components': 3,
  'Vocdoni Protocol': 4 // Last
}

const sdkSidebarIDOrder = {
  'sdk/reference/sdk-reference': -1, // First
  // All other elements are 0 by default
  'sdk/reference/changelog': 1 // Last
}

// Removes autogenerated API sidebar- this is broken.
function skipAPI (items) {
  return items.filter(({label}) => {
    return (
      // Exclude vocdoni-api folder, this folder needs swagger-generated sidebar
      label != 'vocdoni-api'
    )
  })
}

function sortItems (items) {
  // Sort sidebar items by label according to sidebarLabelOrder
  return items.sort((i1, i2) => {
    return (
      (sidebarLabelOrder[i1.label] || 0) - (sidebarLabelOrder[i2.label] || 0)
    )
  })
}

// Adds api sidebar items from './docs/vocdoni-api/sidebar.js', filters out index file
function addAPI (items) {
  // Define root api sidebar item
  const apiItem = {
    type: 'category',
    label: 'Vocdoni API',
    link: {
      type: 'doc',
      id: 'vocdoni-api/vocdoni-api'
    },
    items: []
  }
  // Get swagger-generated API sidebar items, filter out index doc
  require('./docs/vocdoni-api/sidebar.js').forEach(item => {
    if (item?.type !== 'doc' && item?.label !== 'Vocdoni API') {
      apiItem.items.push(item)
    }
  })
  items.push(apiItem)
  return items
}

function toTitleCase (str) {
  return str.charAt(0).toUpperCase() + str.substr(1).toLowerCase()
}

function modifySDKReference (items) {
  for (var index1 in items) {
    if (
      items[index1].type == 'category' &&
      items[index1].label == 'Vocdoni SDK'
    ) {
      const SDKCategory = items[index1]
      for (var index2 in SDKCategory.items) {
        if (
          SDKCategory.items[index2]?.type == 'category' &&
          SDKCategory.items[index2]?.label == 'reference'
        ) {
          // Modify reference category: add link and capitalize label
          referenceCategory = {
            ...SDKCategory.items[index2],
            label: 'Reference',
            link: {
              type: 'doc',
              id: 'sdk/reference/sdk-reference'
            }
          }
          // Capitalize category labels
          for (var index3 in referenceCategory?.items) {
            if (referenceCategory.items[index3].label != null) {
              referenceCategory.items[index3].label = toTitleCase(
                referenceCategory.items[index3].label
              )
            }
          }
          // Sort sidebar items by ID according to sdkSidebarIDOrder
          referenceCategory.items = referenceCategory.items.sort((i1, i2) => {
            return (
              (sdkSidebarIDOrder[i1.id] || 0) - (sdkSidebarIDOrder[i2.id] || 0)
            )
          })
          SDKCategory.items[index2] = referenceCategory
        }
      }
      items[index1] = SDKCategory
    }
  }
  return items
}

module.exports = async function sidebarItemsGenerator ({
  defaultSidebarItemsGenerator,
  ...args
}) {
  const sidebarItems = await defaultSidebarItemsGenerator(args)
  return modifySDKReference(addAPI(skipAPI(sortItems(sidebarItems))))
}
