/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars = {
  getStarted: [{type: 'autogenerated', dirName: 'get-started'}],
  // sdk: [{type: 'autogenerated', dirName: 'sdk'}],
  // sdk: require("./docs/sdk/sidebars-api"),
  sdk: [
    {
      type: 'category',
      label: 'Vocdoni SDK',
      link: {
        type: 'doc',
        id: 'sdk/sdk',
      },
      collapsed: false,
      items: require("./docs/sdk/sidebars-api").api
    },
    {
      type: 'doc',
      id:  'sdk/changelog',
    },
  ],
  vocdoniApi: [
    {
      type: "category",
      label: "Vocdoni",
      link: {
        type: "doc",
        id: 'vocdoni-api/vocdoni-api',
      },
      collapsed: false,
      items: require("./docs/vocdoni-api/sidebar.js"),
    },
  ],
};

module.exports = sidebars;
