// Removes autogenerated API sidebar- this is broken.
function skipAPI (items) {
  return items.filter(({label}) => {
    return (
      // Exclude vocdoni-api folder, this folder needs swagger-generated sidebar
      label != 'vocdoni-api'
    )
  })
}

// Adds api sidebar items from './docs/vocdoni-api/sidebar.js', filters out index file
function addAPI (items) {
  // Define root api sidebar item
  const apiItem = {
    type: 'category',
    label: 'Vocdoni API',
    link: {
      type: 'doc',
      id: 'vocdoni-api/vocdoni-api'
    },
    items: []
  }
  // Get swagger-generated API sidebar items, filter out index doc
  require('./docs/vocdoni-api/sidebar.js').forEach(item => {
    if (item?.type !== 'doc' && item?.label !== 'Vocdoni API') {
      apiItem.items.push(item)
    }
  })
  items.push(apiItem)
  return items
}

module.exports = async function sidebarItemsGenerator ({
  defaultSidebarItemsGenerator,
  ...args
}) {
  const sidebarItems = await defaultSidebarItemsGenerator(args)
  return addAPI(skipAPI(sidebarItems))
}
