import {
  Balance,
  Button,
  Election,
  ElectionActions,
  ElectionDescription,
  ElectionHeader,
  ElectionQuestions,
  ElectionResults,
  ElectionSchedule,
  ElectionStatusBadge,
  ElectionTitle,
  HR,
  Image,
  Markdown,
  OrganizationAvatar,
  OrganizationDescription,
  OrganizationHeader,
  OrganizationName,
  QuestionsConfirmation,
  SpreadsheetAccess,
  VoteButton,
} from '@vocdoni/chakra-components';
import {ElectionProvider, OrganizationProvider} from '@vocdoni/react-providers';
import React from 'react';

import {AspectRatio, Box, Flex} from '@chakra-ui/react';
// Add react-live imports you need here
const ReactLiveScope = {
  React,
  ...React,
  Flex,
  Box,
  AspectRatio,
  Image,
  ElectionProvider,
  ElectionHeader,
  ElectionTitle,
  ElectionSchedule,
  ElectionResults,
  ElectionStatusBadge,
  ElectionDescription,
  ElectionQuestions,
  ElectionActions,
  Election,
  QuestionsConfirmation,
  SpreadsheetAccess,
  VoteButton,
  OrganizationProvider,
  OrganizationAvatar,
  OrganizationDescription,
  OrganizationHeader,
  OrganizationName,
  Balance,
  Button,
  HR,
  Image,
  Markdown,
};
export default ReactLiveScope;
