name: API security review

on:
  workflow_dispatch:
    inputs:
      dummyLogLevel:
        description: 'Dummy Log Level'
        required: false
        default: 'warning'
        type: choice
        options: [info, warning, debug] 
  push:
    branches: 
      - main
      - 'DOPS-400-*'
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'DOPS-400-*'
env:
  API_SPECS_FILE_PATH: swaggers/vocdoni-api.yaml

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  spectral_cli:
    name: Spectral CLI
    runs-on: ubuntu-latest
    if: false           ## false = skip
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set myvars
        id: myvars
        run: |
          branchname=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )
          dateinsecs=$(date +%s)
          githashshort=$(git rev-parse --short HEAD)
          echo "BRANCH_NAME=$branchname" >> $GITHUB_OUTPUT
          echo "GIT_HASH_SHORT=$githashshort" >> $GITHUB_OUTPUT
          echo "DATE_IN_SECS=$dateinsecs" >> $GITHUB_OUTPUT
          if [[ "$branchname" != "develop" ]] && [[ "$branchname" != "main" ]]; then
            echo "BRANCH_NAME=test" >> $GITHUB_OUTPUT   
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Spectral and initial rulesets
        run: |
          npm install @stoplight/spectral-cli
          npm install @stoplight/spectral-owasp-ruleset

      - name: Setup Spectral rulesets
        run: |
          echo 'extends: ["spectral:oas"]' > .spectral_oas.yaml
          echo 'extends: ["@stoplight/spectral-owasp-ruleset"]' > .spectral_owasp.yaml
          mkdir -p _out/

      - name: Run Spectral - ruleset OAS (junit)
        run: |
          set -o pipefail
          npx spectral lint ${{ env.API_SPECS_FILE_PATH }} -r .spectral_oas.yaml -f junit -o _out/spectral_oas.junit 
          set +o pipefail

      - name: Run Spectral - ruleset OWASP (junit)
        if: ${{ success() }} || ${{ failure() }}
        run: |
          set -o pipefail
          npx spectral lint ${{ env.API_SPECS_FILE_PATH }} -r .spectral_owasp.yaml -f junit -o _out/spectral_owasp.junit
          set +o pipefail

      - name: Archive Spectral reports
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: API security reports
          path: _out/*.*

      - name: Publish and embed Spectral Results (OpenAPI, junit)
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: spectral-results-oas
        if: always()    
        #if: false        ## false = bypass (don't exec)
        with:
          files: _out/spectral_oas.junit
          check_name: "Report OpenAPI"
          comment_mode: always 
          job_summary: false 
          compare_to_earlier_commit: true
          report_individual_runs: true 
          report_suite_logs: any 

      - name: Publish and embed Spectral Results (OWASP, junit)
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: owasp-results-junit
        if: always()    
        #if: false        ## false = bypass (don't exec)
        with:
          files: _out/spectral_owasp.junit
          check_name: "Report OWASP APISec Top10"
          comment_mode: always 
          job_summary: false 
          compare_to_earlier_commit: true
          report_individual_runs: true 
          report_suite_logs: any 

  spectral_action:
    name: Spectral GH Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download and setup Spectral Rulesets
        run: |
          echo 'extends: ["spectral:oas", "https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.2.0/dist/ruleset.js"]' > .spectral.yaml

      - name: Run Spectral GH Action
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: ${{ env.API_SPECS_FILE_PATH }}